import * as z from "zod";
import { CodeBlockPanel } from "./CodeBlockPanel";
import { PRISM_CODE_BLOCK_STYLES } from "./codeBlockFitting";

const DEFAULT_TREE = `presentation-templates/
|-- Code/
|   |-- settings.json
|   |-- CoverSlide.tsx
|   |-- CodeExplanationSplitSlide.tsx
|   \`-- codeBlockFitting.ts`;

const DEFAULT_HIGHLIGHTS = [
  {
    label: "settings.json",
    description: "Defines template metadata and available layouts.",
  },
  {
    label: "Schema",
    description: "Controls the data shape generated by AI.",
  },
  {
    label: "TSX Layout",
    description: "Renders the validated content into slide HTML.",
  },
];

const HighlightSchema = z.object({
  label: z.string().min(3).max(26).meta({
    description: "Short file, folder, or concept label highlighted beside the tree.",
  }),
  description: z.string().min(12).max(120).meta({
    description: "Short note explaining the highlighted file, folder, or concept.",
  }),
});

export const layoutId = "file-tree-structure-slide";
export const layoutName = "File Tree with Notes Slide";
export const layoutDescription =
  "A title and description layout with a formatted tree block and adjacent notes.";
export const slideLayoutId = layoutId;
export const slideLayoutName = layoutName;
export const slideLayoutDescription = layoutDescription;

export const Schema = z.object({
  title: z.string().min(6).max(44).default("Template Folder Structure").meta({
    description: "Main slide heading.",
  }),
  description: z.string().min(20).max(220).default(
    "This structure shows how layouts, schemas, settings, and shared utilities are organized."
  ).meta({
    description: "Short supporting text shown below the title.",
  }),
  rootLabel: z.string().min(3).max(36).default("servers/nextjs/app").meta({
    description: "Root folder label shown above the file tree.",
  }),
  tree: z.string().min(30).max(900).default(DEFAULT_TREE).meta({
    description: "Tree content using ASCII-style indentation.",
  }),
  highlights: z.array(HighlightSchema).min(3).max(5).default(DEFAULT_HIGHLIGHTS).meta({
    description: "Right-side notes explaining important files, folders, or concepts.",
  }),
});

export type SchemaType = z.infer<typeof Schema>;

function normalizeHighlights(highlights?: Partial<SchemaType>["highlights"]) {
  const source = Array.isArray(highlights) && highlights.length
    ? highlights
    : DEFAULT_HIGHLIGHTS;

  return source.slice(0, 5).map((item, index) => ({
    label: item?.label || DEFAULT_HIGHLIGHTS[index % DEFAULT_HIGHLIGHTS.length].label,
    description: item?.description || DEFAULT_HIGHLIGHTS[index % DEFAULT_HIGHLIGHTS.length].description,
  }));
}

const CodeSlide15FileTreeStructure = ({ data }: { data: Partial<SchemaType> }) => {
  const highlights = normalizeHighlights(data.highlights);
  const highlightTitleSize = highlights.length > 4 ? 15 : 16;
  const highlightBodySize = highlights.length > 4 ? 13 : 14;

  return (
    <>
      <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet" />
      <style>{PRISM_CODE_BLOCK_STYLES}</style>
      <div
        className="relative flex h-[720px] w-[1280px] flex-col overflow-hidden p-[53px]"
        style={{
          backgroundColor: "var(--background-color,#101B37)",
          fontFamily: "var(--body-font-family,Nunito Sans)",
        }}
      >
        <h2 className="shrink-0 text-[50px] font-medium leading-[105%]" style={{ color: "var(--background-text,#ffffff)" }}>
          {data.title || "Template Folder Structure"}
        </h2>
        <p className="mt-[10px] max-w-[1050px] shrink-0 text-[20px] leading-[135%]" style={{ color: "var(--background-text,#CAD5E2)" }}>
          {data.description || "This structure shows how layouts, schemas, settings, and shared utilities are organized."}
        </p>
        <div className="mt-[22px] grid min-h-0 flex-1 grid-cols-[minmax(0,1.55fr)_minmax(0,0.95fr)] gap-[22px]">
          <CodeBlockPanel
            title="File Tree"
            fileName={data.rootLabel || "servers/nextjs/app"}
            language="tree"
            content={data.tree || DEFAULT_TREE}
            maxWidth={684}
            maxHeight={338}
            maxFontSize={17}
            minFontSize={7}
            showLanguage={false}
          />
          <div
            className="flex min-h-0 flex-col overflow-hidden rounded-[18px] border p-[18px]"
            style={{
              backgroundColor: "var(--card-color,#0F172B80)",
              borderColor: "var(--stroke,#1D293D80)",
            }}
          >
            <p className="shrink-0 text-[19px] leading-none" style={{ color: "var(--background-text,#ffffff)" }}>
              Notes
            </p>
            <div className="mt-[14px] grid min-h-0 flex-1 auto-rows-fr gap-[10px] overflow-hidden">
              {highlights.map((item, index) => (
                <div
                  key={`${item.label}-${index}`}
                  className="min-h-0 overflow-hidden rounded-[10px] border px-[14px] py-[12px]"
                  style={{
                    backgroundColor: "var(--card-color,#1D293D4D)",
                    borderColor: "var(--stroke,#1D293D80)",
                  }}
                >
                  <p
                    className=" font-medium leading-[120%]"
                    style={{
                      color: "var(--background-text,#f1f4ff)",
                      fontSize: `${highlightTitleSize}px`,
                    }}
                  >
                    {item.label}
                  </p>
                  <p
                    className="mt-[6px] overflow-hidden leading-[130%]"
                    style={{
                      color: "var(--background-text,#aebbe5)",
                      fontSize: `${highlightBodySize}px`,
                    }}
                  >
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default CodeSlide15FileTreeStructure;
