export default {
  id: "education-workshop-seminar-practice-review",
  templateId: "workshop-seminar",
  themeId: "practice-review",
  name: "研修工作坊 - 实践复盘",
  category: "education",
  visual: {
    primary: "14505A",
    accent: "18A999",
    secondary: "F6C85F",
    warning: "EF8354",
    background: "F7F5EE",
    surface: "FFFFFF",
    title: "12263A",
    body: "435466",
    layout: "education-workshop-practice-review",
    variant: "practice-review",
  },
  layoutSchema: {
    defaultCoverLayout: "education-workshop-practice-cover",
    defaultContentLayout: "education-workshop-practice-board",
    allowedLayouts: [
      "education-workshop-practice-cover",
      "education-workshop-practice-flow",
      "education-workshop-practice-cocreation",
      "education-workshop-practice-feedback",
      "education-workshop-practice-retro",
      "education-workshop-practice-actions",
      "education-workshop-practice-summary",
      "title",
      "content",
    ],
  },
};
